# -*- coding: utf-8 -*-
"""electricity_bulletin

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MMcCNO16X_mav4SMJqvCoWOlXjn8UQMk
"""

import pandas as pd
!pip install us
import us

#read the data

raw = pd.read_csv(
    "/content/Average_retail_price_of_electricity (1).csv",
    skiprows=4
)

raw.head()

#cleaning unnecessary top rows
electricity = raw[
    raw["description"]
    .str.startswith("Residential :", na=False)
].copy()

electricity.head()

#extracting US states


valid_states = [s.name for s in us.states.STATES]
valid_states.append("United States")


electricity["State"] = (
    electricity["description"]
    .str.replace("Residential :", "", regex=False)
    .str.strip()
)

electricity = electricity[
    electricity["State"].isin(valid_states)
].copy()

electricity.head()

# remove DC
electricity = electricity[
    electricity["State"] != "District Of Columbia"
].copy()
"District Of Columbia" in electricity["State"].values

# all date columns
date_cols = electricity.columns[3:-1]   # exclude State

map_rows = []

for _, row in electricity.iterrows():

    state = row["State"]

    # latest non-null value
    values = row[date_cols]

    latest_col = values.last_valid_index()
    latest_value = values[latest_col]

    remarks = ""

    # only write a remark if latest month isn't the dataset's last month
    if latest_col != date_cols[-1]:
        remarks = f"{latest_col} used"

    map_rows.append([
        state,
        latest_value,
        remarks
    ])

map_table = pd.DataFrame(
    map_rows,
    columns=["Name", "Values", "Remarks"]
)

map_table['Name'].count()

#sort by electricity price
map_table = (
    map_table
    .sort_values("Values", ascending=False)
    .reset_index(drop=True)
)

#display(map_table.style.hide(axis="index"))
map_table

#copy the entire above table in csv to datawrapper for the choropleth chart

#Prices and Dynamics
comparison_states = [
    "New York",
    "United States",
    "California",
    "Connecticut",
    "Florida",
    "Massachusetts",
    "New Jersey",
    "Pennsylvania",
    "Texas",
    "Vermont"
]

date_cols = list(electricity.columns[3:-1])

latest_idx = len(date_cols) - 1

latest_month = date_cols[latest_idx]
previous_month = date_cols[latest_idx - 1]
year_ago_month = date_cols[latest_idx - 12]

month_name = latest_month[:3]
baseline_month = f"{month_name} 2019"

summary_rows = []

for state in comparison_states:

    row = electricity[
        electricity["State"] == state
    ].iloc[0]

    val_2019 = row[baseline_month]
    val_yoy = row[year_ago_month]
    val_mom = row[previous_month]
    val_curr = row[latest_month]

    summary_rows.append({
        "State": state,
        baseline_month: val_2019,
        year_ago_month: val_yoy,
        previous_month: val_mom,
        latest_month: val_curr,
        "MoM %": (val_curr / val_mom - 1) * 100,
        "YoY %": (val_curr / val_yoy - 1) * 100,
        "Since 2019 %": (val_curr / val_2019 - 1) * 100
    })

prices_dynamics = pd.DataFrame(summary_rows)

prices_dynamics[
    ["MoM %", "YoY %", "Since 2019 %"]
] = prices_dynamics[
    ["MoM %", "YoY %", "Since 2019 %"]
].round(2)

prices_dynamics = prices_dynamics.set_index("State").T

prices_dynamics

#Long-Term Dynamics

long_term = (
    electricity[
        electricity["State"].isin([
            "United States",
            "New York"
        ])
    ]
    .set_index("State")[date_cols]
    .T
    .reset_index()
    .rename(
        columns={
            "index": "Date",
            "United States": "U.S."
        }
    )
)

long_term = long_term[
    ["Date", "U.S.", "New York"]
]

long_term["U.S."] = long_term["U.S."].round(2)
long_term["New York"] = long_term["New York"].round(2)

#display(long_term.style.hide(axis="index"))
long_term

#converting datatype in columns
long_term["U.S."] = pd.to_numeric(long_term["U.S."], errors="coerce")
long_term["New York"] = pd.to_numeric(long_term["New York"], errors="coerce")

# Difference Table

difference = long_term.copy()

difference["U.S."] = pd.to_numeric(
    difference["U.S."],
    errors="coerce"
)

difference["New York"] = pd.to_numeric(
    difference["New York"],
    errors="coerce"
)

difference["Difference"] = (
    difference["New York"]
    - difference["U.S."]
)

difference["Difference Percent"] = (
    difference["Difference"]
    / difference["U.S."]
    * 100
).round(1)


#display(difference.style.hide(axis="index"))
difference

#Rolling 12M Difference in cents
#setup
rolling_avg = difference.copy()

rolling_avg["Rolling Average Difference"] = (
    rolling_avg["Difference"]
    .rolling(window=12)
    .mean()
)
rolling_avg = rolling_avg.dropna(
    subset=["Rolling Average Difference"]
)
rolling_table = pd.DataFrame(
    [
        rolling_avg["Rolling Average Difference"].round(2).tolist(),
        rolling_avg["Difference"].round(2).tolist()
    ],
    index=[
        "Rolling average difference in dollars",
        "Difference in dollars"
    ],
    columns=rolling_avg["Date"]
)

rolling_table

#Rolling 12M Difference in percentage
rolling_avg_pct = difference.copy()

rolling_avg_pct["Rolling Average Percent"] = (
    difference["Difference Percent"]
    .rolling(window=12)
    .mean()
)

rolling_avg_pct = rolling_avg_pct.dropna(
    subset=["Rolling Average Percent"]
)
rolling_percent_table = pd.DataFrame(
    [
        rolling_avg_pct["Rolling Average Percent"].round(2).tolist(),
        rolling_avg_pct["Difference Percent"].round(2).tolist()
    ],
    index=[
        "Rolling average difference in percent",
        "Difference in percent"
    ],
    columns=rolling_avg_pct["Date"]
)

rolling_percent_table