# -*- coding: utf-8 -*-
"""natural_gas_bulletin

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17nRsslRF0RQXie9EeBSMW_O0EreKuhCO
"""

import pandas as pd
!pip install us
import us

gas = pd.read_excel(
    "/content/Natural Gas Data Aug 2026.xls",
    sheet_name="Data 1"
)

#Data Cleaning

# Extract state names from row 1
headers = gas.iloc[1].astype(str)

# Keep original dates column name
headers.iloc[0] = "Date"

# Use first line / first words before " Price of"
headers = headers.str.split(" Price of").str[0]

gas.columns = headers

# Remove metadata rows
gas = gas.iloc[2:].reset_index(drop=True)

gas.head()

valid_states = [s.name for s in us.states.STATES]
valid_states.append("U.S.")

keep_cols = ["Date"]

for col in gas.columns:
    if col in valid_states:
        keep_cols.append(col)

gas = gas[keep_cols]

#converting data format
gas["Date"] = pd.to_datetime(gas["Date"])

#keep only 2001 onwards
gas = gas[
    gas["Date"] >= "2001-01-01"
].copy()

gas["Date"] = gas["Date"].dt.strftime("%b %Y")

print(gas.columns[:10])
print(gas["Date"].min())
print(gas["Date"].max())

# Choropleth Map

map_rows = []

latest_row = gas.iloc[-1]

latest_month = latest_row["Date"]

for state in gas.columns[1:]:  # skip Date

    state_series = pd.to_numeric(
        gas[state],
        errors="coerce"
    )

    last_valid_idx = state_series.last_valid_index()

    latest_value = state_series.loc[last_valid_idx]

    used_month = gas.loc[last_valid_idx, "Date"]

    remarks = ""

    if used_month != latest_month:
        remarks = (
            f"Latest month ({latest_month}) unavailable; "
            f"{used_month} value used"
        )

    map_rows.append([
        state,
        latest_value,
        remarks
    ])

gas_map = pd.DataFrame(
    map_rows,
    columns=[
        "Name",
        "Values",
        "Remarks"
    ]
)

gas_map["Values"] = gas_map["Values"].round(2)

gas_map = (
    gas_map
    .sort_values("Values", ascending=False)
    .reset_index(drop=True)
)

gas_map

#Prices and Dynamics
#Setup comparison states
comparison_states = [
    "California",
    "Connecticut",
    "Florida",
    "Massachusetts",
    "New Jersey",
    "New York",
    "Pennsylvania",
    "Texas",
    "Vermont",
    "U.S."
]

#determine comparison month names
latest_idx = len(gas) - 1

latest_month = gas.iloc[latest_idx]["Date"]
previous_month = gas.iloc[latest_idx - 1]["Date"]
year_ago_month = gas.iloc[latest_idx - 12]["Date"]

month_name = latest_month[:3]
baseline_month = f"{month_name} 2019"

print(baseline_month)
print(year_ago_month)
print(previous_month)
print(latest_month)

#insert imputation logic for empty months
def get_latest_available(target_month, state):

    row_idx = gas.index[
        gas["Date"] == target_month
    ][0]

    while row_idx >= 0:

        value = pd.to_numeric(
            gas.loc[row_idx, state],
            errors="coerce"
        )

        if pd.notna(value):
            return value

        row_idx -= 1

    return None

# Build the table

prices_dynamics = pd.DataFrame(index=[
    f"Price, $/MCF, {baseline_month}",
    f"Price, $/MCF, {year_ago_month}",
    f"Price, $/MCF, {previous_month}",
    f"Price, $/MCF, {latest_month}",
    "% Month-on-month",
    "% Year-on-year",
    "% Since 2019"
])

for state in comparison_states:

    val_2019 = get_latest_available(
        baseline_month,
        state
    )

    val_yoy = get_latest_available(
        year_ago_month,
        state
    )

    val_mom = get_latest_available(
        previous_month,
        state
    )

    val_curr = get_latest_available(
        latest_month,
        state
    )

    prices_dynamics[state] = [
        val_2019,
        val_yoy,
        val_mom,
        val_curr,
        (val_curr - val_mom) / val_mom * 100,
        (val_curr - val_yoy) / val_yoy * 100,
        (val_curr - val_2019) / val_2019 * 100
    ]

# rounding
prices_dynamics = prices_dynamics.round(2)

prices_dynamics

# Long-Term Dynamics

long_term = gas[
    ["Date", "U.S.", "New York"]
].copy()

long_term["U.S."] = pd.to_numeric(
    long_term["U.S."],
    errors="coerce"
)

long_term["New York"] = pd.to_numeric(
    long_term["New York"],
    errors="coerce"
)

long_term = long_term.round(2)

long_term

#Price Difference

difference = long_term.copy()

difference["Difference in $/MCF"] = (
    difference["New York"]
    - difference["U.S."]
)

difference["Difference in percent"] = (
    difference["Difference in $/MCF"]
    / difference["U.S."]
    * 100
)

difference = difference.round(2)

difference

#Rolling 12M Average Difference in Percent
# Rolling 12M Average Difference in Percent

rolling_percent = difference.copy()

rolling_percent["Rolling Average Difference in Percent"] = (
    rolling_percent["Difference in percent"]
    .rolling(window=12)
    .mean()
)

rolling_percent = rolling_percent.dropna(
    subset=["Rolling Average Difference in Percent"]
)

rolling_percent_table = pd.DataFrame(
    [
        rolling_percent["Rolling Average Difference in Percent"]
        .round(2)
        .tolist(),

        rolling_percent["Difference in percent"]
        .round(2)
        .tolist()
    ],
    index=[
        "Rolling Average Difference in Percent",
        "Difference in Percent"
    ],
    columns=rolling_percent["Date"]
)

rolling_percent_table